name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing greeting
        run: echo "Hello World!"
      - name: Printing Goodbye
        run: echo "Done - Goodbye"
